version: '3.7'
services:
  mysql_db_container:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: userservice
      MYSQL_USER: testuser
      MYSQL_PASSWORD: testpassword
    ports:
      - 3306:3306
    volumes:
      - mysql_db_data_container:/var/lib/mysql
  adminer_container:
    image: adminer:latest
    environment:
      ADMINER_DEFAULT_SERVER: mysql_db_container
    ports:
      - 8080:8080

volumes:
  mysql_db_data_container:

  # mysql -uroot -prootpassword

  # create user 'testuser'@'%' identified by 'testpassword';
  # grant all on userservice.* to 'testuser'@'%';